### PR TITLE
Added: What is the subset of C# supported by the NEO compiler and NEO VM

### PR DESCRIPTION
**Pull request by mwherman2000**
Added to **Developer Documentation**: [What is the subset of C# supported by the NEO compiler and NEO VM](https://github.com/mwherman2000/neo-persistibleclasses/blob/master/README.md#what-is-the-subset-of-c-supported-by-the-neo-compiler-and-neo-vm)

### CODE REVIEW

**Comment by metachris** [comment]
I would not put this first in the list, but perhaps last. This list is general Developer Documentation, and yours is quite specific.

**Comment by mwherman2000** [comment]
Edit 2: Should we perhaps start to add subsections to the Developer Documentation?

I think that's a good idea ...thought it for the PR but I'm glad you brought it up.  I'm accumulating a fair bit of C# content that could easily command it's own subsection.

Going back to your comment about "yours is quite specific", "What is the subset of C# supported by the NEO compiler and NEO VM" is in fact the #1 topic for C#.NEO developers.  It should be more accessible.

**Comment by metachris** [comment]
👍 

About it being specific, I meant that a lot of developers are looking at this, also those not not interested in C# specifics, but perhaps just general docs, or python, or JS for instance.

**Comment by metachris** [comment]
Please re-order your addition to the back of the list. Btw, usually this repo is listing the things in alphabetical manner.

**Comment by mwherman2000** [comment]
Closing this PR.  I've added the link here: <https://github.com/mwherman2000/neo-csharpcoe#neo-csharpcoe-top-10-list-of-resources-for-cneo-developers>

**Pull request closed without merging**
