### PR TITLE
Deprecation marker and link removals

### PR DESCRIPTION
**Pull request by rockacola**
Following links are remained on the documents and marked as deprecated:

* http://explorer.neoverse.io/
* https://trello.com/b/6TngvuLf/neoblockchaindevelopment
* https://antchain.xyz/

Following links are removed completed

* [Python smart contracts](https://github.com/CityOfZion/awesome-neo/resources/python-examples.md#code-examples)

Following Exchange is considered irrelevant to NEO/GAS trading and hence removed:

* [CryptoMate](https://cryptomate.co.uk/buy-neo/)

Following merchandise page is considered as obsolete and hence removed:

- [HODL Apparels](https://www.redbubble.com/people/hecadothbelial?ref=artist_title_name)
- [NEO Sticker](https://www.redbubble.com/people/tshirtdesign/works/27735886-neo-former-antshares-logo?p=sticker)
- [NEO Sticker](https://www.redbubble.com/people/rahbwormlord/works/27799013-neo-smart-economy-hd-logo?p=sticker)
- [NEO Sticker](https://www.redbubble.com/people/with-care/works/27126848-neo?grid_pos=2&p=sticker&rbs=3fd9cbb7-0d6a-4a49-9ae5-a4943ccfcf7d&ref=shop_grid)

`neon-wallet` release link is now replaced with its release page.

There are few 'Slack' word and URL references, that are now replaced with correct 'Discord' 
reference.

### CODE REVIEW

**Comment by metachris** [comment]
👍

**Comment by rockacola** [comment]
Re-sync latest change from `master`. There should have no more conflicts now.

**Comment by metachris** [comment]
Could you please resolve the conflicts? Then we can merge this :)

**Comment by rockacola** [comment]
lol has this not been merged yet?!
sure I'll jump on it :)

**Comment by rockacola** [comment]
Re-sync latest change from `master`. There should have no more conflicts now.

**Comment by metachris** [comment]
nice, thanks!

**Pull request merged**
