### PR TITLE
Several fixes

### PR DESCRIPTION
**Pull request by corollari**
Changes:
- Added a travis build check that prevents the appearance of dead links
- Removed many projects which were unmaintained and outdated
- Fixed links to moved documents
- Removed duplicated references

Overall, in this PR I avoided making any major change that could be controversial and haven't added any new resource.

The explanation for every change is in its respective commit message.

### CODE REVIEW

**Comment by ixje** [comment]
Nice! 👍

**Comment by corollari** [comment]
@canesin could you also enable Travis in the repo?

**Comment by canesin** [comment]
@corollari why Travis in an awesome repo ? :thinking:

**Comment by ixje** [comment]
> Added a travis build check that prevents the appearance of dead links

**Comment by canesin** [comment]
@ixje could you ping @lllwvlvwlll on Slack ? It appears GH changed how the webhooks works.

**Comment by ixje** [comment]
done

**Pull request merged**
