### PR TITLE
Reordering subsections

### PR DESCRIPTION
**Pull request by Nikolaj-K**
The list grew historically and I put the bullet points in an order

### CODE REVIEW

**Comment by Nikolaj-K** [comment]
@ixje You're right, added.

**Comment by Nikolaj-K** [comment]
@ixje Why have 3 levels? In any case, I'm not against those changes.

**Comment by ixje** [comment]
@Nikolaj-K I didn't intend to force three levels. That's also why I said
> if you choose to make it 3 levels that is
:)

If you choose to keep it 2 (which I'm fine with as well), then `whitepapers` should be removed from the ToC, as that's a 3rd level heading (to it's 2nd level parent, being 'Documentation'). I hope that clarifies it better. Otherwise hit me up on slack

**Comment by Nikolaj-K** [comment]
kk, did it like that now, with 2 levels everywhere

**Comment by revett** [comment]
@Nikolaj-K Why is this better than A-Z ordering?

**Comment by Nikolaj-K** [comment]
@revett I think e.g. resources like neo.docs are more relevant for the folks coming here for resources, while I don't think the first letter of the bullet points are obvious keywords.

**Comment by jhepkema** [comment]
@Nikolaj-K in my opinion, the Table of Contents should give enough overview for developers and non-developers. A-Z ordering feels natural and makes lists easier to read; I think that if you feel like the bullet points are not obvious keywords, we would be better off changing the headers to something more obvious than re-ordering the list. Just my 0.02 GAS.

**Pull request closed without merging**
